### ISSUE TITLE
Cut release for GHC 8.6.1

### ISSUE THREAD

**Issue by bgamari** [haskell/unix#117]
Thanks in advance!

**Comment by hvr** [comment]
Documenting for posterity what we discussed privately: GHC 8.6.1 is supposed to stay w/ unix-2.7.2.2 (or at most with a conservative 2.7.3.0 if the need should arise) and *not* with unix-2.8 as not all breaking changes planned for 2.8 had landed yet and I want to avoid having yet another disruptive unix-2.9 follow shortly after.

*(GHC 8.6.1alpha was using an unreleased snapshot of unix-2.8; otoh that's not a big deal as the alpha releases come with no API stability guarantees anyway; the GHC 8.6.1beta however is expected to ship with unix-2.7.2.2)*

**Comment by nh2** [comment]
Hey, can we release 2.8 soon?

Many applications are just bugged without proper support for `O_CLOEXEC`. Commit c7d88b3612fdf74a7964a670d6e79128f97f46b0 added support for it exactly 3 years ago.

It would be really awesome if this change could be released so that we can fix buggy Fd / forking behaviour in many applications.

For me the coupling to some GHC release isn't even that important, as long as functions are available in some release I can use that permit opening Fds race-free.

Thanks!
