### ISSUE TITLE
problematic openFile with named pipes

### ISSUE THREAD

**Issue by vwwv** [haskell/unix#120]
Not sure whether this issue should be here, or on `base`, but I could not submit it to base.

- while `openFile`'ng named pipes for `ReadMode` works fine, on `WriteMode` or `AppendMode` it throws `openFile: does not exist (No such device or address)`; and on `WriteReadMode`, it opens it, but seem not able to write to it (the process hearing on the other side didn't hear anything).

- `writeFile` and `appendFile` works though.

- using stack `resolver: lts-12.4`

**Comment by hvr** [comment]
Since the `openFile` operation is in fact provided by the `base` package you should file this upstream at http://ghc.haskell.org/trac/ghc/newticket?component=libraries/base

Also note the stack resolver information is not very useful as most of us don't use the 3rd party tool stack; it's much more useful if you just tell us which GHC and/or base version you're using.
