### ISSUE TITLE
Need a way to check file existence without throwing an exception

### ISSUE THREAD

**Issue by yaitskov** [haskell/unix#198]
Hi,

I tried to use GHC stack-trace generation feature to debug and locate an issue.
I discovered GHC prints strack traces for all thrown exceptions.
No matter whether it was caught or not.
If such operation is executed in a loop it floods trace log and it is much harder to notice real problems and investigate, because stack traces caused by real errors are dissolved among routine ones.

Adding a flag to GHC to avoid the problem described above [seems pretty hard](https://gitlab.haskell.org/ghc/ghc/-/issues/20536).
So I propose to extend current `unix` API to give an opportunity to check file existence without throwing an exception as a regular outcome.

**Comment by hs-viktor** [comment]
Have you considered `tryIO` to convert exceptions to `Either IOError a`...

**Comment by hs-viktor** [comment]
Reading the issue more closely, I see that the request to provide some variant of `stat` that returns an `Either IOError` or similar result, rather than throwing an `IOError`.  This is perhaps reasonable, if a tad repetitive to do across all the various functions where one might want this.

Indeed any *does file exist* test is generally a `TOCTOU` race condition. More compelling might be variants of `open` et. al. that don't throw exceptions, and return `Either IOError Fd`

We would first need to clone the machinery behind:
```
     throwErrnoPathIfMinus1Retry,
     throwErrnoPathIfMinus1Retry_,
     throwErrnoPathIfNullRetry,
     throwErrnoPathIfRetry,
     throwErrnoPath,
     throwErrnoPathIf,
     throwErrnoPathIf_,
     throwErrnoPathIfNull,
     throwErrnoPathIfMinus1,
     throwErrnoPathIfMinus1_,
     throwErrnoTwoPathsIfMinus1_
```
to return `IO (Either IOError r)` instead of `IO r`, and then use these to construct non-throwing variants of various functions.  This is not rocket science, but would likely touch many modules if to be done broadly.

Too late for 2.8 at this point I expect.  But if someone wants to scope out how much work this would be, and it looks manageable, I am mostly supportive of providing exception-free interfaces.  I myself find exception at EOF frequently annoying.  But throwing on actually unexpected I/O conditions does simplify code, without having to run in 'ExceptT IOError IO`, lifting all base monad functions, ...

**Comment by hasufell** [comment]
> More compelling might be variants of open et. al. that don't throw exceptions, and return Either IOError Fd

I'm not sure what's so interesting about that. That's exactly what `try` does: https://hackage.haskell.org/package/base-4.16.2.0/docs/Control-Exception.html#v:try

```
Prelude System.Posix Control.Exception> :t \fp om fm -> try . openFd fp om fm
\fp om fm -> try . openFd fp om fm
  :: Exception e =>
     FilePath
     -> OpenMode -> Maybe FileMode -> OpenFileFlags -> IO (Either e Fd)
```

**Comment by hs-viktor** [comment]
> > More compelling might be variants of open et. al. that don't throw exceptions, and return Either IOError Fd
> 
> I'm not sure if that's too interesting, because that's exactly what `try` does: https://hackage.haskell.org/package/base-4.16.2.0/docs/Control-Exception.html#v:try
> 
> ```
> Prelude Control.Exception System.Posix> :t \fp om fm -> try @IOError . openFd fp om fm
> \fp om fm -> try @IOError . openFd fp om fm
>   :: FilePath
>      -> OpenMode
>      -> Maybe FileMode
>      -> OpenFileFlags
>      -> IO (Either IOError Fd)
> ```

Note that you were careful to catch only `IOError` exceptions, but this is easy to get wrong.  And in any case, the OP's issue is that with `-xc` these would still be logged, even though they're caught.  Of course `-xc` is rather a corner case, and it is not clear that the cost of supporting a full panel of non-throwing interfaces is justified by a desire to reduce noise in debug logging. Perhaps a better approach is more tunable `-xc` logging (a filter that is called to decide which exceptions to log).

**Comment by hasufell** [comment]
I'm inclined to close this as won'tfix or upstream.

If we were to create a non-exception API, we'd probably want that to be *additional* and then my guess is to make this maintainable it would require some dirty CPP hacks. All in all I'm not sure that's worth it.

**Comment by hs-viktor** [comment]
Yes, closing as won't fix is a potentially reasonable option.
