### ISSUE TITLE
Release 2.8.4.0

### ISSUE THREAD

**Issue by hasufell** [haskell/unix#307]
## changelog

* add `haveStatx`
* fix `statx.stx_mnt_id` detection on buggy glibc, see [GHC #24072](https://gitlab.haskell.org/ghc/ghc/-/issues/24072)
* allow building with newer filepath/os-string
* Use `throwErrnoIfMinus1Retry` for mkstemp

**Comment by hasufell** [comment]
Only pending PR: https://github.com/haskell/unix/pull/306

@Bodigrim @hs-viktor

**Comment by hasufell** [comment]
My idea was to get this into 9.6.4: https://gitlab.haskell.org/ghc/ghc/-/issues/24017

**Comment by vdukhovni** [comment]
Let's not include the os-string flag as a bug-fix release (2.8.4).  Instead this should be 2.9.0. With 2.8.x adding only bug fixes and perhaps some small additions.

**Comment by hasufell** [comment]
> Let's not include the os-string flag as a bug-fix release (2.8.4).  Instead this should be 2.9.0. With 2.8.x adding only bug fixes and perhaps some small additions.

Why?

**Comment by vdukhovni** [comment]
> > Let's not include the os-string flag as a bug-fix release (2.8.4).  Instead this should be 2.9.0. With 2.8.x adding only bug fixes and perhaps some small additions.
> 
> Why?

I am concerned about under-tested unexpected build issues for various packages. How confident are you that in complex dependency graphs we won't end up with conflicting outcomes?

**Comment by vdukhovni** [comment]
Sounds largely reasonable, unless 9.8.2 should instead be 9.9-dev, to be released with 9.10.1 when that's ready.

**Comment by Bodigrim** [comment]
Delaying `os-string` until 9.10.1 would be way too conservative IMO, we need to gain some experience with it and split `os-string` / `filepath-1.5` sooner than later. I imagine by GHC 9.10 `os-string` and `filepath-1.5` are to be boot packages.

Realistically, since `unix` is a boot package, Cabal has very little incentive to rebuild it with non-default set of flags, so you are almost guaranteed to be safe. This is not the case for `hackage-security` and `Cabal` / `Cabal-syntax` split.

**Comment by vdukhovni** [comment]
I'll trust your judgement on this. This is outside my area of competence, beyond the scars building cabal-install 3.[0246]. :-(
